"use client"
import { ObsidianSidebar } from "@/components/obsidian-sidebar"
import { TopHeader } from "@/components/top-header"
import { KanbanBoard, KanbanColumn, KanbanTask } from "@/components/ui/trello-kanban-board"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"
import { KanbanSquare, Search, Plus, Loader2 } from "lucide-react"

export default function TasksKanbanPage() {
  const router = useRouter()
  const [columns, setColumns] = useState<KanbanColumn[]>([
    { id: "pending", title: "To Do", tasks: [] },
    { id: "in-progress", title: "In Progress", tasks: [] },
    { id: "review", title: "Review", tasks: [] },
    { id: "completed", title: "Done", tasks: [] },
  ])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function loadTasks() {
      try {
        const { data, error } = await supabase.from("tasks").select("*")
        if (error) throw error

        if (data) {
          const newCols = [
            { id: "pending", title: "To Do", tasks: [] as KanbanTask[] },
            { id: "in-progress", title: "In Progress", tasks: [] as KanbanTask[] },
            { id: "review", title: "Review", tasks: [] as KanbanTask[] },
            { id: "completed", title: "Done", tasks: [] as KanbanTask[] },
          ]

          data.forEach(task => {
            const mappedTask: KanbanTask = {
              id: task.id,
              title: task.name,
              description: task.details,
              labels: task.task_type ? [task.task_type] : [],
              assignee: task.user_owner
            }
            
            const col = newCols.find(c => c.id === task.status)
            if (col) {
              col.tasks.push(mappedTask)
            } else {
              // fallback to pending
              newCols[0].tasks.push(mappedTask)
            }
          })
          setColumns(newCols)
        }
      } catch (err) {
        console.error("Failed to load tasks:", err)
      } finally {
        setLoading(false)
      }
    }
    loadTasks()
  }, [])

  const handleTaskMove = async (taskId: string, fromColId: string, toColId: string) => {
    try {
      await supabase
        .from("tasks")
        .update({ status: toColId })
        .eq("id", taskId)
    } catch (err) {
      console.error("Error moving task:", err)
    }
  }

  const handleTaskAdd = async (columnId: string, title: string) => {
    try {
      const { data, error } = await supabase
        .from("tasks")
        .insert([{ name: title, status: columnId }])
        .select()
        .single()
        
      if (error) throw error

      if (data) {
        // Optimistic UI updates
        setColumns(currentCols => currentCols.map(col => {
          if (col.id === columnId) {
            // Need to remove the temporary client-side task generated by the component
            // and replace it with the DB one to ensure IDs match
            return {
              ...col,
              tasks: col.tasks.map(t => t.title === title && t.id.startsWith("task-") ? {
                ...t, id: data.id
              } : t)
            }
          }
          return col
        }))
      }
    } catch (err) {
      console.error("Error adding task:", err)
    }
  }

  return (
    <div className="flex w-full h-screen overflow-hidden bg-[var(--color-brand-obsidian)]">
      <div className="hidden md:block w-[84px] shrink-0 relative z-50">
        <ObsidianSidebar />
      </div>

      <div className="flex-1 flex flex-col h-full overflow-hidden relative z-10 w-full">
         <TopHeader />
         
         <div className="flex-1 flex flex-col min-h-0">
            <div className="px-8 pt-8 pb-6 border-b border-white/5 bg-[var(--color-brand-surface-1)]">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                  <h2 className="font-heading text-3xl font-extrabold tracking-tight mb-1 text-[var(--color-brand-text)] flex items-center gap-3">
                    <KanbanSquare size={28} className="text-[var(--color-brand-violet)]" />
                    Task Board
                  </h2>
                  <p className="text-[var(--color-brand-muted)] text-sm">Organize requests, manage project milestones, and track progress.</p>
                </div>
                
                <div className="flex items-center gap-3">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-brand-muted)]" size={16} />
                    <input 
                      type="text" 
                      placeholder="Search tasks..." 
                      className="w-full sm:w-64 bg-black/40 border border-white/10 rounded-lg py-2 pl-9 pr-4 text-sm focus:border-[var(--color-brand-violet)]/50 focus:outline-none transition-all placeholder:text-white/30"
                    />
                  </div>
                  <button 
                    onClick={() => router.push('/dashboard/tasks/new')}
                    className="border border-[var(--color-brand-violet)] bg-[#09090b] hover:bg-[var(--color-brand-violet)]/10 text-[var(--color-brand-violet)] font-bold px-4 py-2 h-[38px] rounded-lg flex items-center justify-center gap-2 transition-colors shadow-[0_0_10px_rgba(138,43,226,0.15)] text-sm whitespace-nowrap"
                  >
                    <Plus size={16} strokeWidth={3} /> New Task
                  </button>
                </div>
              </div>
            </div>

            <div className="flex-1 overflow-x-auto overflow-y-hidden p-8 no-scrollbar bg-black/20">
              {loading ? (
                <div className="flex h-full items-center justify-center text-[var(--color-brand-muted)]">
                  <Loader2 size={32} className="animate-spin" />
                </div>
              ) : (
                <KanbanBoard 
                  columns={columns} 
                  onColumnsChange={setColumns}
                  onTaskMove={handleTaskMove}
                  onTaskAdd={handleTaskAdd}
                  onTaskClick={(id) => router.push(`/dashboard/tasks/${id}/edit`)}
                  className="h-full min-h-0"
                />
              )}
            </div>
         </div>
      </div>
    </div>
  )
}
