import { TalentMock } from "@/components/spotlight-drawer"

export const MOCK_TALENT: TalentMock[] = [
  {
    id: "1",
    name: "Anya Taylor-Joy",
    category: "Film & TV",
    location: "London, UK",
    verifiedAt: "2 mins ago",
    momentumGrowth: 42,
    managerName: "Sarah Halprin",
    managerEmail: "shalprin@caa.mock",
    brandConflicts: ["Dior", "Tiffany & Co."],
  },
  {
    id: "2",
    name: "Fred Again..",
    category: "Electronic Music",
    location: "London, UK",
    verifiedAt: "1 hour ago",
    momentumGrowth: 115,
    managerName: "Sam Evitt",
    managerEmail: "sam@methodmusic.mock",
    brandConflicts: ["Apple"],
  },
  {
    id: "3",
    name: "Lewis Hamilton",
    category: "Sports",
    location: "Monaco",
    verifiedAt: "4 hours ago",
    momentumGrowth: 18,
    managerName: "Penni Thow",
    managerEmail: "pthow@copper.mock",
    brandConflicts: ["Monster Energy", "Tommy Hilfiger", "IWC"],
  },
  {
    id: "4",
    name: "Rosalía",
    category: "Pop Music",
    location: "Barcelona, ES",
    verifiedAt: "1 day ago",
    momentumGrowth: 30,
    managerName: "Celia G",
    managerEmail: "celia.g@sonymusic.mock",
    brandConflicts: ["Acne Studios", "Coca-Cola"],
  },
  {
    id: "5",
    name: "Zendaya",
    category: "Film & TV",
    location: "Los Angeles, CA",
    verifiedAt: "2 days ago",
    momentumGrowth: 28,
    managerName: "Kevin Turen",
    managerEmail: "kturen@wme.mock",
    brandConflicts: ["Valentino", "Bulgari", "Lancome"],
  },
  {
    id: "6",
    name: "Jack Harlow",
    category: "Hip Hop",
    location: "Louisville, KY",
    verifiedAt: "12 hours ago",
    momentumGrowth: 56,
    managerName: "Chris Thomas",
    managerEmail: "chris@generationnow.mock",
    brandConflicts: ["New Balance", "KFC"],
  },
  {
    id: "7",
    name: "Emma Raducanu",
    category: "Sports",
    location: "London, UK",
    verifiedAt: "3 days ago",
    momentumGrowth: 12,
    managerName: "Max Eisenbud",
    managerEmail: "meisenbud@img.mock",
    brandConflicts: ["Porsche", "Tiffany & Co.", "Dior", "British Airways"],
  },
  {
    id: "8",
    name: "Central Cee",
    category: "Hip Hop",
    location: "London, UK",
    verifiedAt: "5 hours ago",
    momentumGrowth: 88,
    managerName: "Bello",
    managerEmail: "bello@livewire.mock",
    brandConflicts: ["Nike", "Jacquemus"],
  }
]

export const MOCK_AGENCIES = [
  { id: "1", name: "Creative Artists Agency (CAA)", type: "Talent Agency", location: "Los Angeles", rosterSize: 3420, topClients: ["Anya Taylor-Joy", "Tom Hanks"] },
  { id: "2", name: "William Morris Endeavor (WME)", type: "Talent Agency", location: "Los Angeles", rosterSize: 4100, topClients: ["Zendaya", "Dwayne Johnson"] },
  { id: "3", name: "Method Music", type: "Management", location: "London", rosterSize: 45, topClients: ["Fred Again..", "Disclosure"] },
  { id: "4", name: "Copper", type: "Management", location: "New York", rosterSize: 12, topClients: ["Lewis Hamilton"] },
  { id: "5", name: "Sony Music", type: "Record Label", location: "Global", rosterSize: 5000, topClients: ["Rosalía", "Travis Scott"] },
]

export const MOCK_CAMPAIGNS = [
  { id: "1", name: "Q4 Luxury Holiday", status: "Active", talentCount: 12, lastUpdated: "2 hours ago" },
  { id: "2", name: "Gen-Z Tech Launch", status: "Scouting", talentCount: 45, lastUpdated: "1 day ago" },
  { id: "3", name: "Global Sports Drink", status: "Review", talentCount: 8, lastUpdated: "3 days ago" },
  { id: "4", name: "European Auto Show", status: "Archived", talentCount: 22, lastUpdated: "2 weeks ago" },
]
